attributes =  ['happy', 'bastard', 'mischievous', 'bashful', 'cute', 
'sexy', 'bitch', 'devil', 'enviable', 'sarcastic', "saddo", "crazy",
'beautiful', 'sleepy', 'grumpy', 'horny', 'curious', 'positive', 
'cynical', 'boring', 'vain', 'stupid', 'greedy', 'passionate', 
'evil', 'dopey', 'caring', 'arrogant', 'rude', 'lazy', 'flirt',
'outgoing', 'cool', 'daring', 'engaging', 'honest', 'cheap', 
'fussy', 'jealous', 'perfectionist', 'smug', 'reliable', 'devilish',
'witty', 'funny', 'sad', 'angry', 'enamoured', 'angel', 'nurturing']

attributes_nsfw = ['kinky', 'sub', 'dom', 'switch', 'tabboo', 
'slut', 'spankable', 'daddy', 'boss', 'mistress', 'sir', 'master', 
'tied', 'stimulated', 'orgasmic', 'sensual']

insults = [
"The closest you'll come to a brainstorm is a light drizzle.",  
"Honestly, I'm just impressed you could read this.",  
"Your family tree didn't have enough branches.",  
"Your face just made me agnostic.",  
"I'm still deciding whether you're the weakest link or the missing link.",  
"I have neither the time nor the crayons necessary to explain this to you.",  
"You are an oxygen bandit.",  
"I've had bowel movements more attractive than you.",  
'You look like a "before" picture.',  
"You could have been an extra in Chernobyl.",  
"What doesn't kill you disappoints the rest of us.",  
"Did you develop your personality in car a crash?",  
"I smell smoke. Were you thinking too hard again?",  
"Being bitter won't make you prettier.",  
"Out of all the sperm to win the race...",  
"You'll go far someday. And I hope you stay there.",  
"Your gene pool needs more chlorine.",  
"I will not have a battle of wits with an unarmed ,opponent.",  
"It's impossible to underestimate you.",  
"The only time you're not as dumb as you look is when I close my eyes.",  
"Imagine how many crises would have been averted if your parents bothered to use a condom.",  
"You look like someone fed you after midnight.",  
"Even Bob Ross would call you a mistake.",  
"If I gave you a penny for your thoughts, I'd get change back.",  
'Our parents told us we could be anything, and you chose "disappointment".',  
"Your birth control of choice appears to be your personality.",  
"If you’re going to be two-faced, at least make one of them cute.",  
"If your IQ were just a little higher you could be an idiot.",  
"You're not the dumbest person alive, but you better hope they're taking vitamins.",  
"I'd love to help you out. Which way did you get in?",  
"Light travels faster than sound, which is why you seemed bright until you spoke.",  
"You're as bright as beige.",  
"You look like something I drew with my left hand.",  
            ]